apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  labels:
    gitadd : webedit
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mywebs
  template:
    metadata:
      name: myweb
      labels:
        app: mywebs
    spec:
      containers:
      - name: myweb
        image: 544093516502.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-repo-for-app:v1.0.0
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: myweb
spec:
  ports:
    - name: webport
      port: 8080
      targetPort: 80
  selector:
    app: mywebs
  type: ClusterIP
---
